### PR TITLE
added date, binary data filter check, supporting of case when, subtra…

### PR DESCRIPTION
**Pull request by sudiptasamanta**
I have moved from my previous account sudipta2016 to sudiptasamanta and will continue here.

"added date, binary data filter check, supporting of case when, subtraction, max, min

Hi Russel,

Your woks is great and it help me a lot in my project.
I have added some more features.
Please review and merge if it looks fine."

As per your reply: "Please run the tests via mvn clean verify. Some of the tests do not pass."

OUT PUT:

Tests run: 28, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.767 sec - in com.github.vincentrussell.query.mongodb.sql.converter.QueryConverterIT

Results :

Tests run: 28, Failures: 0, Errors: 0, Skipped: 0
it passes all test cases

could you please respond me any test cases which is getting failed ?
Thank you for your co-operation.
[compile_output.log](https://github.com/vincentrussell/sql-to-mongo-db-query-converter/files/4474560/compile_output.log)

### CODE REVIEW

**Comment by vincentrussell** [comment]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.vincentrussell.query.mongodb.sql.converter.QueryConverterTest
Tests run: 134, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 1.816 sec <<< FAILURE!
Failed tests:   writeMaxMinCaseWhen(com.github.vincentrussell.query.mongodb.sql.converter.QueryConverterTest): expected:<...      "$date": 15778[17000000(..)
  writeCaseWhenBinaryDataFilterSubtraction(com.github.vincentrussell.query.mongodb.sql.converter.QueryConverterTest): expected:<...      "$date": 15778[17000000(..)
  writeDateFilters(com.github.vincentrussell.query.mongodb.sql.converter.QueryConverterTest): expected:<...      "$date": 15778[17000000(..)

Tests run: 158, Failures: 3, Errors: 0, Skipped: 0

**Comment by vincentrussell** [comment]
I am running on linux.  I am not sure if that's the difference-maker or not.  I have not looked too closely.

**Comment by sudiptasamanta** [comment]
I am using mac.
the os should not create those issues.
Anyway I'll also look at those test cases.

**Comment by vincentrussell** [comment]
Please rebase, fix tests and resubmit the pull request.

Thank you.

**Pull request closed without merging**
