### PR TITLE
Feature/subqueries

### PR DESCRIPTION
**Pull request by plad88**
Hi again Vincentrussell,

This new pull request enables subqueries translated to aggregate steps in a recursive way. It works with every previous feature event joins inside or like a part of them. For example a simple subquery:

`select c.borough from(select borough, cuisine from Restautants limit 2) as c limit 1`

to

`db.Restautants.aggregate([{ 
        	  "$limit": 2 
        	},{ 
        	  "$project": { 
        	    "_id": 0, 
        	    "borough": 1, 
        	    "cuisine": 1 
        	  } 
        	},{ 
        	  "$limit": 1 
        	},{ 
        	  "$project": { 
        	    "_id": 0, 
        	    "borough": 1 
        	  } 
        	}])`

Or a big complex one:

`select t.cuisine as cuisine, max(t.total) as maxi, count(*) as coxi 
from Restaurants as r 
inner join (
select r.cuisine as cuisine, r.borough as borough, trest.totalrestaurats as total 
from Restaurants as r 
inner join (
select cuisine, count(*) as totalrestaurats 
from Restaurants 
group by cuisine
) as trest 
on r.cuisine = trest.cuisine 
order by trest.totalrestaurats desc, cuisine asc, borough 
limit 15
) as t 
on r.cuisine = t.cuisine and r.borough = t.borough 
group by t.cuisine
`

to 

`db.Restaurants.aggregate([{ 
                 "$lookup": { 
                   "from": "Restaurants", 
                   "let": { 
                     "cuisine": "$cuisine", 
                     "borough": "$borough" 
                   }, 
                   "pipeline": [ 
                     { 
                       "$lookup": { 
                         "from": "Restaurants", 
                         "let": { 
                           "cuisine": "$cuisine" 
                         }, 
                         "pipeline": [ 
                           { 
                             "$group": { 
                               "_id": "$cuisine", 
                               "totalrestaurats": { 
                                 "$sum": 1 
                               } 
                             } 
                           }, 
                           { 
                             "$project": { 
                               "cuisine": "$_id", 
                               "totalrestaurats": 1, 
                               "_id": 0 
                             } 
                           }, 
                           { 
                             "$match": { 
                               "$expr": { 
                                 "$eq": [ 
                                   "$$cuisine", 
                                   "$cuisine" 
                                 ] 
                               } 
                             } 
                           } 
                         ], 
                         "as": "trest" 
                       } 
                     }, 
                     { 
                       "$unwind": { 
                         "path": "$trest", 
                         "preserveNullAndEmptyArrays": false 
                       } 
                     }, 
                     { 
                       "$sort": { 
                         "trest.totalrestaurats": -1, 
                         "cuisine": 1, 
                         "borough": 1 
                       } 
                     }, 
                     { 
                       "$limit": 15 
                     }, 
                     { 
                       "$project": { 
                         "_id": 0, 
                         "cuisine": "$cuisine", 
                         "borough": "$borough", 
                         "total": "$trest.totalrestaurats" 
                       } 
                     }, 
                     { 
                       "$match": { 
                         "$and": [ 
                           { 
                             "$expr": { 
                               "$eq": [ 
                                 "$$cuisine", 
                                 "$cuisine" 
                               ] 
                             } 
                           }, 
                           { 
                             "$expr": { 
                               "$eq": [ 
                                 "$$borough", 
                                 "$borough" 
                               ] 
                             } 
                           } 
                         ] 
                       } 
                     } 
                   ], 
                   "as": "t" 
                 } 
               },{ 
                 "$unwind": { 
                   "path": "$t", 
                   "preserveNullAndEmptyArrays": false 
                 } 
               },{ 
                 "$group": { 
                   "_id": "$t.cuisine", 
                   "maxi": { 
                     "$max": "$t.total" 
                   }, 
                   "coxi": { 
                     "$sum": 1 
                   } 
                 } 
               },{ 
                 "$project": { 
                   "cuisine": "$_id", 
                   "maxi": 1, 
                   "coxi": 1, 
                   "_id": 0 
                 } 
               }])
`

There're more examples in "QueryConverterSubqueryTest.java" file and it the ITtest.

Also there's other feature, now alias of fields can be use inside "order" by like in mysql.

Regars

### CODE REVIEW

**Comment by vincentrussell** [comment]
Thank you for your contribution.  The only thing that I don't like is the use of the System properties.   I think I might introduce a QueryConverterBuilder to clean up the arguments used for the QueryConverter.   For right now I'll accept your pull request, but I might make some changes to this before the next release.

Thank you,
Vincent

**Comment by vincentrussell** [comment]
I deprecated the current constructors and added the builder pattern.  Check it out and let me know what you think.

Thanks,
Vincent

**Comment by plad88** [comment]
Cool, I think it's a good idea and a clean way to instanciate it, that can support new features and future options better :-). 

Also, the change of the aggregation's params it's a clearer way. The env vars could be use in docker enviroment but for a normal enviroment i think that it's better like this and you can pass this params in the entrypoint.

I hope the other pull request can be merged, it looks very usefull in other to start adding new project functions

**Comment by vincentrussell** [comment]
I have one other pull request, but I am waiting in the submitter to fix
tests.

Is that the one you are referring to?

**Comment by plad88** [comment]
yes, the one with the case-when, substract, and many more things that looks cool also :-)

**Comment by vincentrussell** [comment]
I'm not sure if it even worked because the tests were broken.

**Pull request merged**
